.PHONY: all

all:
	php graphics/barcode.php
	php graphics/qrcode.php
	php graphics/image.php
	php graphics/blob.php
	php graphics/svg_avatar.php
	php graphics/svg_bar.php
	php graphics/svg_pie.php
	php graphics/svg_plot.php
	php brindille.php
	php cssparser.php
	php delta.php
	php db.php
	php DB/Entity.php
	php DB/SQLite3.php
	php entity.php
	bash errormanager.sh
	php htmldocument.php
	php html_table_to_ods.php
	php http.php
	#php mail_message.php
	#php mustachier.php # Deprecated
	php oauth2_server.php
	php office_totext.php
	php security.php
	php security_otp.php
	php skrivlite.php
	php smartyer.php
	php smtp.php
	php translate.php
	#php webdav_server.php # Unfinished
	php zipreader.php
