<?php
/*
  Part of the KD2 framework collection of tools: http://dev.kd2.org/
  
  Copyright (c) 2001-2016 BohwaZ <http://bohwaz.net/>
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are met:
  1. Redistributions of source code must retain the above copyright notice,
  this list of conditions and the following disclaimer.
  2. Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
  THE POSSIBILITY OF SUCH DAMAGE.
*/

namespace KD2;

// Cette liste donne les noms de pays (forme courte en français) dans l'ordre
// alphabétique comme donné dans l'ISO 3166-1 et les codes alpha-2 correspondants.

// Mis à jour le 13/12/2011 00:39

class Countries_FR
{
	public static $countries = [
		'AF' => 'Afghanistan',
		'ZA' => 'Afrique Du Sud',
		'AX' => 'Åland, Îles',
		'AL' => 'Albanie',
		'DZ' => 'Algérie',
		'DE' => 'Allemagne',
		'AD' => 'Andorre',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctique',
		'AG' => 'Antigua-et-barbuda',
		'SA' => 'Arabie Saoudite',
		'AR' => 'Argentine',
		'AM' => 'Arménie',
		'AW' => 'Aruba',
		'AU' => 'Australie',
		'AT' => 'Autriche',
		'AZ' => 'Azerbaïdjan',
		'BS' => 'Bahamas',
		'BH' => 'Bahreïn',
		'BD' => 'Bangladesh',
		'BB' => 'Barbade',
		'BY' => 'Bélarus',
		'BE' => 'Belgique',
		'BZ' => 'Belize',
		'BJ' => 'Bénin',
		'BM' => 'Bermudes',
		'BT' => 'Bhoutan',
		'BO' => 'Bolivie, L\'état Plurinational De',
		'BQ' => 'Bonaire, Saint-eustache Et Saba',
		'BA' => 'Bosnie-herzégovine',
		'BW' => 'Botswana',
		'BV' => 'Bouvet, Île',
		'BR' => 'Brésil',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgarie',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KY' => 'Caïmans, Îles',
		'KH' => 'Cambodge',
		'CM' => 'Cameroun',
		'CA' => 'Canada',
		'CV' => 'Cap-vert',
		'CF' => 'Centrafricaine, République',
		'CL' => 'Chili',
		'CN' => 'Chine',
		'CX' => 'Christmas, Île',
		'CY' => 'Chypre',
		'CC' => 'Cocos (keeling), Îles',
		'CO' => 'Colombie',
		'KM' => 'Comores',
		'CG' => 'Congo',
		'CD' => 'Congo, La République Démocratique Du',
		'CK' => 'Cook, Îles',
		'KR' => 'Corée, République De',
		'KP' => 'Corée, République Populaire Démocratique De',
		'CR' => 'Costa Rica',
		'CI' => 'Côte D\'ivoire',
		'HR' => 'Croatie',
		'CU' => 'Cuba',
		'CW' => 'Curaçao',
		'DK' => 'Danemark',
		'DJ' => 'Djibouti',
		'DO' => 'Dominicaine, République',
		'DM' => 'Dominique',
		'EG' => 'Égypte',
		'SV' => 'El Salvador',
		'AE' => 'Émirats Arabes Unis',
		'EC' => 'Équateur',
		'ER' => 'Érythrée',
		'ES' => 'Espagne',
		'EE' => 'Estonie',
		'US' => 'États-unis',
		'ET' => 'Éthiopie',
		'FK' => 'Falkland, Îles (malvinas)',
		'FO' => 'Féroé, Îles',
		'FJ' => 'Fidji',
		'FI' => 'Finlande',
		'FR' => 'France',
		'GA' => 'Gabon',
		'GM' => 'Gambie',
		'GE' => 'Géorgie',
		'GS' => 'Géorgie Du Sud-et-les Îles Sandwich Du Sud',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Grèce',
		'GD' => 'Grenade',
		'GL' => 'Groenland',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernesey',
		'GN' => 'Guinée',
		'GW' => 'Guinée-bissau',
		'GQ' => 'Guinée Équatoriale',
		'GY' => 'Guyana',
		'GF' => 'Guyane Française',
		'HT' => 'Haïti',
		'HM' => 'Heard-et-îles Macdonald, Île',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hongrie',
		'IM' => 'Île De Man',
		'UM' => 'Îles Mineures Éloignées Des États-unis',
		'VG' => 'Îles Vierges Britanniques',
		'VI' => 'Îles Vierges Des États-unis',
		'IN' => 'Inde',
		'ID' => 'Indonésie',
		'IR' => 'Iran, République Islamique D\'',
		'IQ' => 'Iraq',
		'IE' => 'Irlande',
		'IS' => 'Islande',
		'IL' => 'Israël',
		'IT' => 'Italie',
		'JM' => 'Jamaïque',
		'JP' => 'Japon',
		'JE' => 'Jersey',
		'JO' => 'Jordanie',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KG' => 'Kirghizistan',
		'KI' => 'Kiribati',
		'KW' => 'Koweït',
		'LA' => 'Lao, République Démocratique Populaire',
		'LS' => 'Lesotho',
		'LV' => 'Lettonie',
		'LB' => 'Liban',
		'LR' => 'Libéria',
		'LY' => 'Libye',
		'LI' => 'Liechtenstein',
		'LT' => 'Lituanie',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macédoine, L\'ex-république Yougoslave De',
		'MG' => 'Madagascar',
		'MY' => 'Malaisie',
		'MW' => 'Malawi',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malte',
		'MP' => 'Mariannes Du Nord, Îles',
		'MA' => 'Maroc',
		'MH' => 'Marshall, Îles',
		'MQ' => 'Martinique',
		'MU' => 'Maurice',
		'MR' => 'Mauritanie',
		'YT' => 'Mayotte',
		'MX' => 'Mexique',
		'FM' => 'Micronésie, États Fédérés De',
		'MD' => 'Moldova, République De',
		'MC' => 'Monaco',
		'MN' => 'Mongolie',
		'ME' => 'Monténégro',
		'MS' => 'Montserrat',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibie',
		'NR' => 'Nauru',
		'NP' => 'Népal',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigéria',
		'NU' => 'Niué',
		'NF' => 'Norfolk, Île',
		'NO' => 'Norvège',
		'NC' => 'Nouvelle-calédonie',
		'NZ' => 'Nouvelle-zélande',
		'IO' => 'Océan Indien, Territoire Britannique De L\'',
		'OM' => 'Oman',
		'UG' => 'Ouganda',
		'UZ' => 'Ouzbékistan',
		'PK' => 'Pakistan',
		'PW' => 'Palaos',
		'PS' => 'Palestinien Occupé, Territoire',
		'PA' => 'Panama',
		'PG' => 'Papouasie-nouvelle-guinée',
		'PY' => 'Paraguay',
		'NL' => 'Pays-bas',
		'PE' => 'Pérou',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Pologne',
		'PF' => 'Polynésie Française',
		'PR' => 'Porto Rico',
		'PT' => 'Portugal',
		'QA' => 'Qatar',
		'RE' => 'Réunion',
		'RO' => 'Roumanie',
		'GB' => 'Royaume-uni',
		'RU' => 'Russie, Fédération De',
		'RW' => 'Rwanda',
		'EH' => 'Sahara Occidental',
		'BL' => 'Saint-barthélemy',
		'SH' => 'Sainte-hélène, Ascension Et Tristan Da Cunha',
		'LC' => 'Sainte-lucie',
		'KN' => 'Saint-kitts-et-nevis',
		'SM' => 'Saint-marin',
		'MF' => 'Saint-martin(partie Française)',
		'SX' => 'Saint-martin (partie Néerlandaise)',
		'PM' => 'Saint-pierre-et-miquelon',
		'VA' => 'Saint-siège (état De La Cité Du Vatican)',
		'VC' => 'Saint-vincent-et-les Grenadines',
		'SB' => 'Salomon, Îles',
		'WS' => 'Samoa',
		'AS' => 'Samoa Américaines',
		'ST' => 'Sao Tomé-et-principe',
		'SN' => 'Sénégal',
		'RS' => 'Serbie',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapour',
		'SK' => 'Slovaquie',
		'SI' => 'Slovénie',
		'SO' => 'Somalie',
		'SD' => 'Soudan',
		'SS' => 'Soudan Du Sud',
		'LK' => 'Sri Lanka',
		'SE' => 'Suède',
		'CH' => 'Suisse',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard Et Île Jan Mayen',
		'SZ' => 'Swaziland',
		'SY' => 'Syrienne, République Arabe',
		'TJ' => 'Tadjikistan',
		'TW' => 'Taïwan, Province De Chine',
		'TZ' => 'Tanzanie, République-unie De',
		'TD' => 'Tchad',
		'CZ' => 'Tchèque, République',
		'TF' => 'Terres Australes Françaises',
		'TH' => 'Thaïlande',
		'TL' => 'Timor-leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinité-et-tobago',
		'TN' => 'Tunisie',
		'TM' => 'Turkménistan',
		'TC' => 'Turks-et-caïcos, Îles',
		'TR' => 'Turquie',
		'TV' => 'Tuvalu',
		'UA' => 'Ukraine',
		'UY' => 'Uruguay',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela, République Bolivarienne Du',
		'VN' => 'Viet Nam',
		'WF' => 'Wallis Et Futuna',
		'YE' => 'Yémen',
		'ZM' => 'Zambie',
		'ZW' => 'Zimbabwe',
	];
}
